[package]
name = "tangue"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.8"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
